# Generated by Django 3.1.5 on 2021-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='value',
            field=models.BigIntegerField(default=0),
        ),
    ]
