# Generated by Django 3.1.5 on 2021-01-26 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0001_initial'),
        ('debit_request', '0002_auto_20210123_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debit',
            name='super_user',
        ),
        migrations.AlterField(
            model_name='debit',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debit',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
    ]
