# Generated by Django 3.1.5 on 2021-01-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_request', '0003_auto_20210125_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Aproved', 'Aproved'), ('Rejected', 'Rejected')], max_length=10),
        ),
    ]
