# Generated by Django 3.1.5 on 2021-01-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_request', '0004_auto_20210126_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Aproved', 'Aproved'), ('Rejected', 'Rejected'), ('Analyzing', 'Analyzing')], max_length=10),
        ),
    ]
